### ISSUE TITLE
Maximum number of runs exceeded error

### ISSUE THREAD

**Issue by Protoncek** [TheByteStuff/RemoteSyslog_Service#4]
Lately i see following warning in my HA logs:

```
Logger: homeassistant.components.automation.syslog_to_syno
Source: helpers/script.py:2005
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 07:03:40 (32639 occurrences)
Last logged: 07:15:28

Syslog to Syno: Maximum number of runs exceeded
```
I export HA logs to my Synology NAS with HA automation.  I checked and log entries are still recorded in my NAS, so i wonder what could cause that warning? Should i purge logs or is there another fault elsewhere?  (although archiving should be done automatically in synology...)

**Comment by TheByteStuff** [comment]
No one has reported this issue before for logging.  It might be helpful to have more context to review such as the automation configuration that you've set up as well as how often you think/anticipate it being called.

I do see some discussion of "Maximum number of runs exceeded" in context of Home Assistant.   It would seem logging is being called when another logging attempt for the automation is still in process or you have it set up as queued and the max queued limit is reached.

Maybe look at the [automation configuration](https://www.home-assistant.io/docs/automation/modes/)  settings and consider changing mode to queued if it is singe (which is default) and if already queued increase the default max of 10.  Could try mode as parallel as well - I haven't tried this, so assuming I haven't messed up the script that may also solve the issue.

**Comment by Protoncek** [comment]
Thanks for the answer!

I already do have automation set to "queued", and i have set "max = 30", which means max 30 waiting messages, correct? So, here's the hack - it seems that at some occasions (at reboot especially) number of log entries is so big that automation (or synology nas) can't cope, so queued messages keep coming beyond max. 
So, the solution would be to increase "max" variable even further. The question remains, though, how high can i safely go... 
i guess that i can try parallel mode also to see if anything odd comes out..

**Comment by TheByteStuff** [comment]
You are welcome!

Good question on how high to make the queue.  If you are getting this max message just at startup then increasing the value may not be a big deal.  If it happens at other times too, then I could see being careful about making it too large a number  just so you don't bog the system down in general.  Never used parallel.  If you are willing to try, I'd be curious to hear how it works.  I'd still be cautious about volume of messages though - queuing has some drain on resources but parallel will open the proverbial flood gate which truly could bog things down.

**Comment by Protoncek** [comment]
Well,  my HA runs on Intel nuc skull canyon (i7cpu)… yeah, i know… absolute overkill… but the speed difference in, say, esphome’s yaml compile comparing with VM inside synology is biiiigg…
Since i have “decent” hardware i guess i can afford to try some boundaries… i’ll so some testing in the following days.

**Comment by TheByteStuff** [comment]
LOL, yeah you've got some good horses for your HA.  I'm running both of my HAs on Synology DS220+s and ESPHome on one of them and they do pretty well with that.    Let me know how it all shakes out.

**Comment by Protoncek** [comment]
I increased max to 50 and i still got error. Then i set it to 100, now it's ok. I counted all entries in my Syno and there are around 70-80 with same time mark, so indeed 50 is too small and 100 is enough, as it seems.
I tried parallel also, but i see no difference. That "max" effects parallel and queued anyway, so i think it doesn't matter - if parallel jobs would go over max i'd get an error anyway.

**Comment by TheByteStuff** [comment]
Sounds like you have it figured out.  Thank you for the follow-up!

**Comment by Protoncek** [comment]
Yes. And it wasn't even addon's fault, so sorry for that... but i admit, i didn't even know about meaning of the "max" value until you pointed me into it, so thanks for your help!

**Comment by TheByteStuff** [comment]
You are welcome.  Don't sweat it.  Your question taught me something - I hadn't looked into those settings before.
