### ISSUE TITLE
Can we use variables/wildcards in logged messages?

### ISSUE THREAD

**Issue by LWHays** [TheByteStuff/RemoteSyslog_Service#5]
I'm a newb, so I'm not sure if this is a feature request or if I'm just not understanding the proper syntax for a currently active capability.

We're using HA and alarmo to create an alarm system, and we'd like it to log to a remote syslog when alarm events happen inside HA, like the alarm was armed, triggered, disarmed, etc.    RemoteSyslog_Service is perfect for that and we had not problems on initial setup or in creating basic automations to log events.

We'd like to include details such as who armed or disarmed the system, and alarmo makes some wildcards available that apparently can be used in push messages.   

https://github.com/nielsfaber/alarmo?tab=readme-ov-file#wildcards

I tried using the alarmo wildcards in the message field of the RemoteSyslog_Service.   Here's what that looks like:

![image](https://github.com/user-attachments/assets/60a39b0b-587b-4a84-b2c8-5c00936b17bd)

However, either I'm messing up the syntax or I'm trying to do something that isn't supported. 

Here's what the logged messages look like on the syslog target machine:

Aug  9 12:06:03 172.31.109.210  hascript Alarm: armed   by
Aug  9 12:06:04 homeassistant homeassistant: 2024-08-09 12:06:03.861 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'arm_mode' is undefined when rendering 'Alarm: armed {{arm_mode}}  by {{changed_by}}'
Aug  9 12:06:04 homeassistant homeassistant: 2024-08-09 12:06:03.867 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'changed_by' is undefined when rendering 'Alarm: armed {{arm_mode}}  by {{changed_by}}'

Any guidance on what I'm doing wrong or should this be a feature request?

Thanks,

LW

**Comment by LWHays** [comment]
Of course as soon as I filed the issue I found the right syntax:

This works:

![image](https://github.com/user-attachments/assets/d307d45d-397d-4fbd-baa3-5cbf1ef664ae)

results:

Aug  9 13:48:27 172.31.109.210  hascript Alarm: "armed armed_away by Firstname Lastname"
Aug  9 13:48:45 172.31.109.210  hascript Alarm disarmed by Firstname Lastname

**Comment by LWHays** [comment]
Thanks very much for the RemoteSyslog_Service!!

**Comment by TheByteStuff** [comment]
Just now getting a chance to catch up on emails/notifications.  Glad you got it worked out & that you are able to use the component.  Hope your project goes well!
